Repository gpn-prototypes/vega-ui, pull requests merged in 2020-05, with the labels that each got.

#23 VEGA-67: Добавить gh экшен для autosquash
  .github/workflows/autosquash.yml
Labels: WIP, autosquash

#37 Update storybook.md
  docs/storybook.md
Labels: CSSSR

#35 Update README.md
  packages/components/dropdown/README.md
Labels: CSSSR

#46 VEGA-65: Создать template для генерации компонентов
  _templates/component/new/package.json.ejs.t
  _templates/component/new/packages/components/README.md.ejs.t
  _templates/component/new/packages/components/component/README.md.ejs.t
  _templates/component/new/packages/components/component/docs/pic-1.png
  _templates/component/new/packages/components/component/package.json.ejs.t
  _templates/component/new/packages/components/component/src/Name.css.ejs.t
  _templates/component/new/packages/components/component/src/Name.stories.tsx.ejs.t
  _templates/component/new/packages/components/component/src/Name.test.tsx.ejs.t
  _templates/component/new/packages/components/component/src/Name.tsx.ejs.t
  _templates/component/new/packages/components/component/src/index.ts.ejs.t
  _templates/component/new/packages/components/index.ts.ejs.t
  _templates/component/new/packages/components/package.json.ejs.t
  _templates/generator/help/index.ejs.t
  _templates/generator/new/hello.ejs.t
  _templates/generator/with-prompt/hello.ejs.t
  _templates/generator/with-prompt/prompt.ejs.t
  docs/new-component.md
  docs/static/new-component/pic-1.png
  lerna.json
  package.json
  yarn.lock
Labels: autosquash

#54 VEGA-80: Добавить Github action, чтобы линковать джировские таски в описание задачи
  .github/workflows/update-pr.yml
Labels: Test OK

#57 VEGA-98: Указать нужную версию ноды в бейджике
  README.md
Labels: Test OK
